scrape_configs:
  - job_name: 'blog-app-metrics'
    metrics_path: '/api/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['localhost:8081']
        labels:
          application: 'Blog-App'